config/routes.rb
Myapp::Application.routes.draw do
  
  resources :matches
  get "view_profile", to: 'users#show'
  get "developers/index"
  get "users/show"
  get "about_us", to: 'developers#index'
  get 'auth/:provider/callback', to: 'users#new'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'users/conversations/:id', to: 'conversations#show'

  get "find_matches", to: "matches#find_matches"
  match '/matches/:id/join', to: 'matches#join', via: [:patch]
  match '/matches/:id/kick', to: 'matches#kick', via: [:patch]
  match '/find_matches/carousel', to: 'matches#carousel', via: [:post]
  
  get "faq", to: 'faq#index'
  
  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  get "home/index"

root to: 'home#index'

end

app/models/user.rb
require 'countries'

class User < ActiveRecord::Base
  GENDERS = ["Male", "Female", "Other"]
  SKILL_LEVELS = ["Beginner", "Rookie", "Amateur", "Intermediate", "Professional"]

  validates :name, presence: true, length: { in: 2..255 }
  validates :desc, length: { maximum: 65535 }
  validates :email, presence: true, length: { in: 5..254 }
  validates :birthday, presence: true
  validates :gender, presence: true
  validates :postcode, presence: true, length: { in: 3..10 }
  validates :country, presence: true
  validates :skill_level, presence: true
  validate :birthday_must_be_in_the_past
  validate :gender_must_be_within_range
  validate :country_must_have_length_of_2
  validate :skill_level_must_be_within_range
  # Validation: Birthday date must be in the past, unless you (will) have a time machine.
  def birthday_must_be_in_the_past
    errors.add(:birthday, "must be in the past") if !birthday.blank? and birthday > Date.today
  end
  # Validation: Gender must be one of the values specified in GENDERS.
  def gender_must_be_within_range
    errors.add(:gender, "must be selected") if !gender.blank? and !gender.between?(0, GENDERS.length - 1)
  end
  # Validation: Country code string must have a length of 2.
  def country_must_have_length_of_2
    errors.add(:country, "must be selected") if !country.blank? and country.length != 2
  end
  # Validation: Skill level must be one of the values specified in SKILL_LEVELS.
  def skill_level_must_be_within_range
    errors.add(:skill_level, "must be selected") if !skill_level.blank? and !skill_level.between?(0, SKILL_LEVELS.length - 1)
  end

  has_many :conversations, :foreign_key => :sender_id

  # Login/registration.
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      # If user already exists, don't update the user's data from Google except for image.
      if find_by(email: auth.info.email)
        user.image = auth.info.image.split("?")[0]
        user.save
        return user
      else
        user.uid = auth.uid
        user.provider = auth.provider
        user.name = auth.info.name
        user.image = auth.info.image.split("?")[0]
        user.email = auth.info.email
        user.birthday = auth.extra.raw_info.birthday
        user.gender = auth.extra.raw_info.gender
      end
    end
  end

  # Returns either (in fallback order):
  #   Postcode concatenated with country name,
  #   Postcode concatenated with country code,
  #   Postcode or country name or country code.
  def location
    c = Country.find_country_by_alpha2(country)
    country_name = !c.nil? ? c.name : nil
    if (postcode and country)
      return postcode + ", " + (country_name or country)
    else
      return (postcode or country_name or country)
    end
  end

  # Returns age of user.
  def age
    if birthday
      now = Time.now.utc.to_date
      return now.year - birthday.year - ((now.month > birthday.month || (now.month == birthday.month && now.day >= birthday.day)) ? 0 : 1)
    else
      return nil
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only:[:show, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update]
  before_filter :require_permission, only: [:edit, :update]

  def require_permission
    if current_user != User.find(params[:id])
      redirect_to match_path
    end
  end

  # GET /users/new
  def new
    @user = User.from_omniauth(env["omniauth.auth"]) #get user data from google
    if User.find_by_email(@user.email) #if user already exists then go to home page
      session[:user_id] = @user.id
      redirect_to root_path
    end
      # If not go to registration form for sign up.
  end

  def create
    user_params = params.require(:user).permit(:uid, :provider, :name, :desc, :image, :email, :birthday, :gender, :postcode, :country, :skill_level)
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_path }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # GET /users/1/edit
  def edit
  end

  # GET /users/1
  def show
    @matches = Match.previous_matches(@user.id)
    @myprofile = false # determins whose profile it is
    if current_user.id == @user.id then @myprofile = true end
      # gets conversations of current_user (not used when you are visiting someone else's profile)
      @conversations = Conversation.involving(current_user).order("updated_at DESC")
    end

  def update
    respond_to do |format|
      user_params = params.require(:user).permit(:name, :desc, :birthday, :gender, :postcode, :country, :skill_level)
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_user
    @user = User.find_by_id(params[:id])
    if @user.nil? and current_user then @user = current_user end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/views/users/edit.html.erb
<%= bootstrap_form_for(@user, layout: :horizontal) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <% if @user.image %><%= image_tag(@user.image, alt: "Profile picture", class: "img-thumbnail", size: "128x128") %><% end %>
</div>
<br>
<div class="row">
  <div class="col-sm-12"><div class="panel panel-primary">
    <div class="panel-heading"><h3 class="panel-title">Edit profile</h3></div>
    <div class="panel-body">
      <%= f.text_field :name, label: "Display name" %>
      <%= f.text_field :desc, label: "Biography" %>

      <%= f.form_group :email, label: {text: "Email address"} do %>
      <div style = "padding: 7px 0px;"> <%= @user.email %> </div>
      <% end %>

      <%= f.date_select :birthday, label: "Date of birth", start_year: Date.today.year - 125, end_year: Date.today.year%>
      <%= f.select :gender, [["Male", 0], ["Female", 1], ["Other", 2]], label: "Gender" %>
      <%= f.text_field :postcode, label: "Residential postcode" %>

      <%= f.form_group :country, label: {text: "Residential country"} do %>
      <%= f.country_select :country, { priority_countries: ["AU"]}, { class: "form-control" } %>
      <% end %>

      <%= f.select :skill_level, [["Beginner", 0], ["Rookie", 1], ["Amateur", 2], ["Intermediate", 3], ["Professional", 4]], label: "Skill level" %>

      <%= f.submit "Save", class: "btn btn-primary" %>
      <%= link_to "Cancel", "/view_profile", class: "btn btn-default" %>
    </div>
  </div></div>
</div>

<% end %>

app/views/users/new.html.erb
<%= bootstrap_form_for(@user, layout: :horizontal) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <% if @user.image %><%= image_tag(@user.image, alt: "Profile picture", class: "img-thumbnail", size: "128x128") %><% end %>
</div>
<br>
<div class="row">
  <div class="col-sm-12"><div class="panel panel-primary">
    <div class="panel-heading"><h3 class="panel-title">Registration</h3></div>
    <div class="panel-body">
      <%= f.text_field :name, label: "Display name" %>
      <%= f.text_field :desc, label: "Biography" %>

      <%= f.form_group :email, label: {text: "Email address"} do %>
      <div style = "padding: 7px 0px;"> <%= @user.email %> </div>
      <%= f.hidden_field :email, value: @user.email %>
      <% end %>

      <%= f.select :gender, [["Male", 0], ["Female", 1], ["Other", 2]], label: "Gender" %>

      <%= f.date_select :birthday, label: "Birthday", start_year: Date.today.year - 125, end_year: Date.today.year%>
      <%= f.text_field :postcode, label: "Residential postcode" %>

      <%= f.form_group :country, label: {text: "Residential country"} do %>
      <%= f.country_select :country, { priority_countries: ["AU"]}, { class: "form-control" } %>
      <% end %>

      <%= f.select :skill_level, [["Beginner", 0], ["Rookie", 1], ["Amateur", 2], ["Intermediate", 3], ["Professional", 4]], label: "Skill level" %>

      <%= f.hidden_field :provider, :value => @user.provider %>
      <%= f.hidden_field :uid, :value => @user.uid %>
      <%= f.hidden_field :image, :value => @user.image %>
      
      <%= f.submit "Sign up", class: "btn btn-primary" %>
    </div>
  </div></div>
</div>

<% end %>

app/views/users/show.html.erb
<div class="row">
  <div style="float: left; padding-left: 10px;">
    <% if @user.image %><%= image_tag(@user.image, alt: "Profile picture", class: "img-thumbnail", size: "128x128") %><% end %>
  </div><div style="float: left; padding-left: 10px;padding-top: 10px;">
    <h1><%= @user.name %></h1>
    <h3><i><%= @user.desc %></i></h3>
  </div>
</div>
<br>
<% if current_user and current_user.id != @user.id %>
<%= link_to "Send Message", "#", class: "btn btn-success start-conversation", "data-sid" => current_user.id, "data-rip" => @user.id %><br><br>
<% end %>
<div class="row">
  <% if @myprofile %><div class="col-sm-8"><% else %><div class="col-sm-12"><% end %><div class="panel panel-primary">
    <%# Profile panel. %>
    <div class="panel-heading"><h3 class="panel-title">Profile</h3></div>
    <% if @myprofile %>
      <div class="panel-body">
    <% else %>
      <div class="panel-body">
    <% end %>
      <%# Display email to own user only. %>
      <% if @myprofile %>
        <p><strong>Email address:</strong>
        <%= @user.email %></p>
      <% end %>

      <%# Display birthday to own user or age to public. %>
      <% if @myprofile %>
        <p><strong>Date of birth:</strong>
        <%= @user.birthday ? @user.birthday : "Unspecified" %></p>
      <% else %>
        <p><strong>Age:</strong>
        <%= @user.birthday ? @user.age : "Unspecified" %></p>
      <% end %>

      <%# Display gender to public. %>
      <p><strong>Gender:</strong>
      <%= @user.gender ? User::GENDERS[@user.gender] : "Unspecified" %></p>

      <%# Display location to own user only. %>
      <% if @myprofile %>
        <p><strong>Residential location:</strong>
        <%= (@user.postcode or @user.country) ? @user.location : "Unspecified" %></p>
      <% end %>

      <%# Display skill level to public. %>
      <p><strong>Skill level:</strong>
      <%= @user.skill_level ? User::SKILL_LEVELS[@user.skill_level] : "Unspecified" %></p>

      <%# Display edit button to own user only. %>
      <% if @myprofile %>
        <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-default" %>
      <% end %>
    </div>
  </div></div>

  <% if @myprofile %><div class="col-sm-4"><div class="panel panel-primary">
    <div class="panel-heading"><h3 class="panel-title">Your Conversations</h3></div>
    <div class="panel-body">
      <div style="height: 184px; overflow-y: auto;">
        <% if @conversations.any? %>
          <ul class="media-list">
            <% @conversations.each do |conversation| %>
              <li class="media">
                <%= image_tag(User.find_by_id(conversation_interlocutor(conversation).id).image, class: "media-object pull-left", size: "60x50") %>
                <div class="media-body">
                  <%= link_to(conversation_path(conversation), class: "conversation", "data-cid" => conversation.id) do -%>
                  <h4 class="media-heading"><%= conversation_interlocutor(conversation).name %></h4>
                  <p><%= conversation.messages.last.nil? ? "No messages" : emojify(truncate(conversation.messages.last.body, length: 35)) %></p>
                  <% end %>
                </div>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>You have no conversations.</p>
        <% end %>
      </div>
    </div>
  </div></div><% end %>
</div>