config/routes.rb
Myapp::Application.routes.draw do
  
  resources :matches
  get "view_profile", to: 'users#show'
  get "developers/index"
  get "users/show"
  get "about_us", to: 'developers#index'
  get 'auth/:provider/callback', to: 'users#new'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'users/conversations/:id', to: 'conversations#show'

  get "find_matches", to: "matches#find_matches"
  match '/matches/:id/join', to: 'matches#join', via: [:patch]
  match '/matches/:id/kick', to: 'matches#kick', via: [:patch]
  match '/find_matches/carousel', to: 'matches#carousel', via: [:post]
  
  get "faq", to: 'faq#index'
  
  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  get "home/index"

root to: 'home#index'

end

app/models/match.rb
require 'open-uri'
require 'cgi'

class Match < ActiveRecord::Base
  has_one :conversation
  MATCH_TYPES = ["Singles", "Doubles", "Men's Singles", "Women's Singles", "Men's Doubles", "Women's Doubles", "Mixed Doubles"]
  MALE_GENDER_VALID_MATCH_TYPES = ["Singles", "Doubles", "Men's Singles", "Men's Doubles", "Mixed Doubles"]
  FEMALE_GENDER_VALID_MATCH_TYPES = ["Singles", "Doubles", "Women's Singles", "Women's Doubles", "Mixed Doubles"]
  OTHER_GENDER_VALID_MATCH_TYPES = ["Singles", "Doubles"]
  GENDER_VALID_MATCH_TYPES = {0 => MALE_GENDER_VALID_MATCH_TYPES,
                              1 => FEMALE_GENDER_VALID_MATCH_TYPES,
                              2 => OTHER_GENDER_VALID_MATCH_TYPES}

  validates :desc, length: { maximum: 96 }
  validates :start, presence: true
  validates :postcode, presence: true
  validates :country, presence: true
  validates :duration_days, presence: true, numericality: true
  validates :duration_hours, presence: true, numericality: true
  validates :court, length: { maximum: 48 }
  validate :start_must_be_in_the_future
  validate :duration_days_must_be_positive
  validate :duration_days_must_be_less_than_5
  validate :duration_hours_must_be_positive
  validate :duration_hours_must_be_less_than_23
  validate :duration_days_and_duration_hours_sum_must_be_positive
  validate :match_type_must_be_confined_to_gender
  # Validation: Start date must be in the future.
  def start_must_be_in_the_future
    errors.add(:start, "must be in the future") if !start.blank? and start < DateTime.now
  end
  # Validation: Duration days must be positive.
  def duration_days_must_be_positive
    errors.add(:duration_days, "must be selected") if !duration_days.blank? and duration_days < 0
  end
  # Validation: Duration days must be less than 5 days. Optional validation.
  def duration_days_must_be_less_than_5
    errors.add(:duration_days, "must be selected") if !duration_days.blank? and duration_days >= 5
  end
  # Validation: Duration hours must be positive.
  def duration_hours_must_be_positive
    errors.add(:duration_hours, "must be selected") if !duration_hours.blank? and duration_hours < 0
  end
  # Validation: Duration hours must be less than 23 hours.
  def duration_hours_must_be_less_than_23
    errors.add(:duration_hours, "must be selected") if !duration_hours.blank? and duration_hours >= 24
  end
  # Validation: Duration hours + duration days must be greater than 0.
  def duration_days_and_duration_hours_sum_must_be_positive
    errors.add(:duration_hours, "must be greater than 0") if !duration_days.blank? and !duration_hours.blank? and duration_days + duration_hours <= 0
  end
  # Validation: Certain genders cannot create certain match types.
  def match_type_must_be_confined_to_gender
    current_user = User.find(player1_id)
    if !current_user.blank? and !GENDER_VALID_MATCH_TYPES[current_user.gender].include?(match_type)
      errors.add(:match_type, "can't be created by you")
    end
  end

  belongs_to :conversation

  def self.created_matches(pid)
  	return Match.find_all_by_player1_id(pid)
  end

  def self.user_matches(pid)
    return Match.where("player1_id = ? or player2_id = ? or player3_id = ? or player4_id = ?", pid, pid, pid, pid)
  end

  def self.previous_matches(pid)
    return Match.user_matches(pid).where("end < ?", Time.now.utc.to_s(:db)).order("end DESC")
  end

  def self.upcoming_matches(pid)
    return Match.user_matches(pid).where("end >= ?", Time.now.utc.to_s(:db)).order("end ASC")
  end

  def self.find_match(user, match_type, after)
    # Filter matches from the following:
    #   Self created matches,
    #   Joined matches,
    #   Gender restricted matches,
    #   Mixed matches filled with gender,
    #   Queried match type,
    #   Queried end date,
    #   Already past matches (using start date).
    #   Full matches.
    matches = Match.all.select do |m|
      m.player1_id != user.id and
      m.player2_id != user.id and
      m.player3_id != user.id and
      m.player4_id != user.id and
      GENDER_VALID_MATCH_TYPES[user.gender].include?(m.match_type) and
      (m.match_type != "Mixed Doubles" or m.players.count { |p| p.gender == user.gender } < 2) and
      (match_type == "Any" or m.match_type == match_type) and
      (after.nil? or !after.is_a?Date or m.end.to_date >= after) and
      m.start > DateTime.now and
      !m.full?
    end

    # Array holding distance between user and filtered matches - currently using
    #   match's first player's postcode as match's postcode.
    match_distances = []
    origin = user.location

    # Populate match_distances.
    matches.each do |match|
      destination = match.location
      url = "https://maps.googleapis.com/maps/api/distancematrix/json?key=#{ENV['GOOGLE_API_KEY']}&origins=#{CGI.escape(origin)}&destinations=#{CGI.escape(destination)}"
      doc = JSON.parse(open(url).read)
      tmp = [match.id]
      if (doc["status"] == "OK" and doc["rows"][0]["elements"][0]["status"] == "OK")
        tmp.push(doc["rows"][0]["elements"][0]["distance"]["value"])
      else
        tmp.push(nil)
      end
      match_distances.push(tmp)
    end

    # Sort and return.
    return match_distances.sort{ |e1, e2| (e1[1] or Float::INFINITY) <=> (e2[1] or Float::INFINITY) }
  end

  # Returns either (in fallback order):
  #   Postcode concatenated with country name,
  #   Postcode concatenated with country code,
  #   Postcode or country name or country code.
  def location
    c = Country.find_country_by_alpha2(country)
    country_name = !c.nil? ? c.name : nil
    if (postcode and country)
      return postcode + ", " + (country_name or country)
    else
      return (postcode or country_name or country)
    end
  end

  # Returns match start date.
  def start_date
    return start
  end

  # Returns match end date.
  def end_date
    return (start and duration_days and duration_hours) ? (start + duration_days.days + duration_hours.hours) : nil
  end

  # Returns players in match.
  def players
    return [User.find_by(id: player1_id), User.find_by(id: player2_id),
    User.find_by(id: player3_id), User.find_by(id: player4_id)].compact
  end
  alias_method :users, :players

  # Returns false if match is not completely filled with players, else true.
  def full?
    if match_type.include?("Doubles") and players.length < 4
      return false
    elsif match_type.include?("Singles") and players.length < 2
      return false
    else
      return true
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user
  before_action :set_match, only: [:show, :edit, :update, :destroy, :join, :kick]
  before_action :host, only: [:edit, :update, :destroy, :kick]
  include MatchesHelper

  # GET /matches
  # GET /matches.json
  def find_matches
    @match_distances = Match.find_match(current_user, "Any", nil)
  end

  # the controller for partial view of carousel which is appended on find_matches.html.erb via ajax
  def carousel
    @match_distances = Match.find_match(current_user, params[:match_type], params[:after].to_date)
    render :partial => 'carousel', :content_type => 'text/html', :locals => {:match_distances => @match_distances}
  end


  # GET /matches/1
  # GET /matches/1.json
  def show
    @conversation = Conversation.find_by_id(@match.conversation_id)
    @messages = @conversation.messages
    @message = Message.new
  end

  # GET /matches
  def index
    @up_matches = Match.upcoming_matches(current_user.id)
    @prev_matches = Match.previous_matches(current_user.id)
  end

  # GET /matches/new
  def new
    @match = Match.new
    # Default values entered for new match.
    #   Postcode is defaulted to user's postcode.
    #   Hours duration is defaulted to 2 hours.
    @match.postcode = current_user.postcode
    @match.duration_hours = 2
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)
    @match.player1_id = current_user.id
    @match.end = @match.end_date

    # Create a conversation for match.
    conv = Conversation.new
    conv.match_id = @match.id
    conv.save!

    @match.conversation_id = conv.id
    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: ['Match was successfully created.', "alert alert-dismissible alert-success"] }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    @match.assign_attributes(match_params)
    @match.end = @match.end_date
    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: ['Match was successfully updated.', "alert alert-dismissible alert-success"] }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # join or leave match
  def join
    pids = get_player_list(@match).map{|p| p.try(:id)} # list of player ids
    status = false
    if can_join(pids) #if possible, join
      status = join_now(@match, current_user.id)
      done = ["joined", "success"]
    elsif pids.include?(current_user.id) #if already joined, then leave
      status = leave_now(@match, current_user.id, @host)
      done = ["left", "warning"]
      if !get_player_list(@match).any? #if there is no more players in match, then destroy
        destroy
        return
      end
    end

    respond_to do |format|
      if status and @match.save
        format.html { redirect_to @match, notice: ['You have succesfully ' + done[0] + ' the match.', "alert alert-dismissible alert-" + done[1]] }
      else
        format.html { redirect_to @match, notice: ['Sorry, your request could not be processed.', "alert alert-dismissible alert-danger"] }
      end
    end
  end

  # host can kick people out of match
  def kick
    status = false
    pid = params[:match][:pid].to_i
    # find and kick player out by setting foreign key to nil
    if (@match.player2_id == pid) then @match.player2_id = nil; status = true
    elsif (@match.player3_id == pid) then @match.player3_id = nil; status = true
    elsif (@match.player4_id == pid) then @match.player4_id = nil; status = true
    end

    respond_to do |format|
      if status and @match.save
        format.html { redirect_to @match, notice: ['Player have been successfully kicked out.', "alert alert-dismissible alert-success" ] }
      else
        format.html { redirect_to @match, notice: ['Sorry, your request could not be processed.', "alert alert-dismissible alert-danger"] }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
   @match.destroy

    respond_to do |format|
      format.html { redirect_to @match, notice: ['You have succesfully left the match.', "alert alert-dismissible alert-warning"]}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
      @host = false
      if current_user and current_user.id == @match.player1_id
        @host = true
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:start, :duration_hours, :duration_days, :court, :desc, :match_type, :pid, :country, :postcode, :after)
    end

    def host
      if (!current_user or current_user.id != @match.player1_id)
        redirect_to root_path
      end
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
    def can_join(pids) #determines if it is possible to join match
        pids = pids.compact #list of ids
        if pids.include?(current_user.id) then return false end
        count = pids.count #number of players
        match_type = @match.match_type

        #if there isnt any room
        if(["Singles", "Men's Singles", "Women's Singles"].include?(match_type)\
            and count > 1)
            return false
        end
        if(["Doubles", "Men's Doubles", "Women's Doubles"].include?(match_type)\
            and count > 3)
            return false
        end
        # 0 = Male, 1 = Female
        #only men can enter men's games
        if(["Men's Singles", "Men's Doubles"].include?(match_type)\
            and current_user.gender != 0)
            return false
        end
        #only women can enter women's games
        if(["Women's Singles", "Women's Doubles"].include?(match_type)\
            and current_user.gender != 1)
            return false
        end
        
        genders = pids.map{|pid| User.find(pid).gender} #genders of players
        if(match_type == "Mixed Doubles"\
            and ( ![0, 1].include?(current_user.gender)\
            or genders.count(current_user.gender) > 1))
            return false
        end

        return true
    end

    def get_player_list(match) #get the list of players
        p = []
        p[0] = User.find_by_id(match.player1_id); 
        p[1] = User.find_by_id(match.player2_id); 
        p[2] = User.find_by_id(match.player3_id); 
        p[3] = User.find_by_id(match.player4_id); 
        return p;
    end

    def join_now(match, pid) #join if there is space (second check)
        joined = false
        if match.player2_id.nil? then match.player2_id = pid; joined = true
        elsif match.player3_id.nil? then match.player3_id = pid ; joined = true
        elsif match.player4_id.nil? then match.player4_id = pid ; joined = true
        end
        return joined
    end

    def leave_now(match, pid, host) #leave match
        left = false
        if match.player2_id == pid then match.player2_id = nil; left = true
        elsif match.player3_id == pid then match.player3_id = nil; left = true
        elsif match.player4_id == pid then match.player4_id = nil; left = true
        end
        #if you are host, if there is someone else in the match, he becomes host
        #otherwise the match is destroyed in the calling method
        if host
            @match.player1_id = nil
            if @match.player2_id
                @match.player1_id, @match.player2_id = @match.player2_id, @match.player1_id
            elsif @match.player3_id
                @match.player1_id, @match.player3_id = @match.player3_id, @match.player1_id 
            elsif @match.player4_id
                @match.player1_id, @match.player4_id = @match.player4_id, @match.player1_id 
            end
            if !@match.player1_id.nil? then left = true end
        end

        return left
    end

    def get_class(match) # returns the class for match which is full/ready
        p_count = get_player_list(match).compact.count
        match_type = match.match_type
        if((["Singles", "Men's Singles", "Women's Singles"].include?(match_type) and p_count == 2) or
            (["Doubles", "Men's Doubles", "Women's Doubles"].include?(match_type) and p_count == 4))
            return "success"
        end
        return ""
    end

    def get_lat_long postcode
        url = "https://maps.googleapis.com/maps/api/geocode/json?address=#{postcode}&components=country:AU"
        doc = JSON.parse(open(url).read)
    
        if (doc["status"] == "OK") 
            latitude = doc["results"][0]["geometry"]["location"]["lat"]
            longtitude = doc["results"][0]["geometry"]["location"]["lng"]
        else
        
            raise "Error parsing data"
        end
        return [latitude, longtitude]
    
    end   

end

app/views/matches/_carousel.html.erb
<script type="text/javascript">
  function refresh() {
      orientatePanels();
      return;
  }
  $(document).ready(refresh);
</script>
    <% match_distances[0..15].each do |match_id, dist|
      match = Match.find_by(id:match_id)
      player1 = User.find_by(id:match.player1_id)
      player2 = User.find_by(id:match.player2_id)
      player3 = User.find_by(id:match.player3_id) %>
      <figure class="carousel-panel"><div class="carousel-content">
        <div style="display: block; height: 50%;">
        <% case match.players.length
           when 1 %>
            <%= image_tag(player1.image, alt: player1.name, class:"carousel_image_one") if player1.image %>
            <h3 class="span7 text-center"><%= player1.name.split.map(&:capitalize).join(' ') %></h3>
        <% when 2 %>
            <div>
              <%= image_tag(player1.image, alt: player1.name, class:"carousel_image_two") if player1.image %>
              <h4 class="carousel_text_two"><%= player1.name.split.map(&:capitalize).join(' ') %></h4>
            </div>
            <% if !player2.nil? %><div>
              <%= image_tag(player2.image, alt: player2.name, class:"carousel_image_two") if player2.image %>
              <h4 class="carousel_text_two"><%= player2.name.split.map(&:capitalize).join(' ') %></h4>
            </div><% end %>
        <% when 3 %>
            <div>
              <%= image_tag(player1.image, alt: player1.name, class:"carousel_image_three") if player1.image %>
              <h4 class="carousel_text_three"><%= player1.name.split.map(&:capitalize).join(' ') %></h4>
            </div>
            <% if !player2.nil? %><div>
              <%= image_tag(player2.image, alt: player2.name, class:"carousel_image_three") if player2.image %>
              <h4 class="carousel_text_three"><%= player2.name.split.map(&:capitalize).join(' ') %></h4>
            </div><% end %>
            <% if !player3.nil? %><div>
              <%= image_tag(player3.image, alt: player3.name, class:"carousel_image_three") if player3.image %>
              <h4 class="carousel_text_three"><%= player3.name.split.map(&:capitalize).join(' ') %></h4>
            </div><% end %>
        <% end %>
        </div>
        <h3 class="text-center"><span class="label label-success"><%= match.start.to_s(:long)%></span></h3>
	    <h3 class="text-center"><span class="label label-danger"><%= match.end.to_s(:long)%></span></h3>
	    <div style="float: none;margin-left: auto;margin-right: auto;width:65%">
          <p class="text-center alert alert-dismissible alert-warning">
            <strong><%= match.match_type%></strong><br/>
            <strong><%= !dist.nil? ? ((dist/1000.0).round(2).to_s + " km away") : "" %></strong>
          </p>
        </div>
        <p class="span7 text-center"><%=link_to("Match Page", match, {:class => "btn btn-info", :target => '_blank'}) %></p>
      </div></figure>
    <% end %>

app/views/matches/carousel.js.erb
$("results").html("<%= raw escape_javascript(render(:partial => 'carousel')) %>")

app/views/matches/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><strong>Edit a match</strong></h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/matches/find_matches.html.erb
<div class="row" style="position:absolute;z-index: 10;padding-left:16%;">
  <div class="col-sm-12"><div class="panel panel-primary">
    <div class="panel-heading"><h3 class="panel-title">Find Matches</h3></div>
    <div class="panel-body">
      <!-- :remote => true makes it an ajax post request which is handled in find_matches.js and update-container div is updated only -->
      <%= form_tag({:action => "carousel"}, {:remote => true, :"data-update-target" => "update-container", class: "form-inline"}) do %>
        <%= submit_tag 'Find', :disable_with => 'Please wait...', :class => "btn btn-success" %>&nbsp
        <div class="form-group">
            <%= select_tag "match_type", options_for_select(["Any"] + Match::GENDER_VALID_MATCH_TYPES[current_user.gender]), class: "form-control" %>
            <label for="match_type"> match on </label>
        </div>
        <div class="form-group">
            <input type="date" name="after">
          <label for="after"> or later</label> 
        </div>
      <% end %>
    </div>
  </div></div>
</div>

<br><br><br><br><br><br><br>

<script type="text/javascript">
  function init() {
      initCarousel();
      return;
  }
  $(document).ready(init);
</script>
<section id="carousel-container">
  <div id="carousel" data-carousel-current-panel-index="0">
    <figure class="carousel-panel-center">
      <%= image_tag("tennis-ball.png", size: "900x900") %>
    </figure>
<!-- this div is updated when you search -->
<div id="update-container">
  <%= render :partial => 'carousel', :locals => {:match_distances => @match_distances} %> <!-- default search results -->
</div>
  </div>
</section>
<div style="text-align: center;">
  <br>
  <div class="btn-group">
    <a id="prev" class="btn btn-primary btn-sm" href="#" title="Previous"><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a id="next" class="btn btn-primary btn-sm" href="#" title="Next"><span class="glyphicon glyphicon-chevron-right"></span></a>
  </div>
  <p class="text-muted" style="text-align: centre;"><i>Use the arrows keys or the mouse to scroll through the results.</i></p>
</div>

app/views/matches/index.html.erb
<script type="text/javascript"> /*hides previous match or upcoming match table depening on radio button selection*/
    $(document).ready(function(){
        $("#previous_tbody").hide();
        $('input[type="radio"]').change(function(){   
            if($(this).attr("value")=="upcoming"){
                $("#previous_tbody").hide();
                $("#upcoming_tbody").show();
            }
            if($(this).attr("value")=="previous"){
                $("#upcoming_tbody").hide();
                $("#previous_tbody").show();
            }
        });
    });
</script>

<%= if notice and notice.is_a?(Array) then content_tag(:div, content_tag(:p, notice[0]), class: notice[1]) end %>

<div class="panel panel-primary">
  <div class="panel-heading"><h3 class="panel-title">My Matches</h3></div>
  <div class="panel-body">
    <div class="panel panel-default"><div class="panel-body">
      <label class="radio-inline"><input type="radio" value="upcoming" name="match_list" checked="checked"><strong>Upcoming</strong></label>
      <label class="radio-inline"><input type="radio" value="previous" name="match_list"><strong>Previous</strong></label>
      <%=link_to("New Match", new_match_path, {:class => "btn btn-success btn-xs", :style => "margin-left: 10px;"})%>
    </div>
  </div>

  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Players</th>
        <th>Start</th>
        <th>End</th>
        <th>Court</th>
        <th>Details</th>
      </tr>
    </thead>

    <%# Shows upcoming match list. %>
    <tbody id="upcoming_tbody">
      <% @up_matches.all.each do |match| %>
        <% p = match.players %>
        <%= content_tag :tr, class: get_class(match) do -%>
          <td>
            <%= link_to(image_tag(p[0].image, size: "30x30", alt: p[0].name), p[0])%>
            <%= link_to(image_tag(p[1].image, size: "30x30", alt: p[1].name), p[1]) if match.player2_id %>
            <%= link_to(image_tag(p[2].image, size: "30x30", alt: p[2].name), p[2]) if match.player3_id %>
            <%= link_to(image_tag(p[3].image, size: "30x30", alt: p[3].name), p[3]) if match.player4_id %>
          </td>
          <td><%= match.start.to_s(:long) %></td>
          <td><%= match.end.to_s(:long) %></td>
          <td><%= match.court %></td>
          <td><%= link_to("Match Page", match, {:class => "btn btn-info btn-sm"}) %></td>
        <% end %>
      <% end %>
    </tbody>

    <%# Shows previous match list. %>
    <tbody id="previous_tbody">
      <% @prev_matches.all.each do |match| %>
        <% p = match.players %>
        <%= content_tag :tr, class: get_class(match) do -%>
          <td>
            <%= link_to(image_tag(p[0].image, size: "30x30", alt: p[0].name), p[0])%>
            <%= link_to(image_tag(p[1].image, size: "30x30", alt: p[1].name), p[1]) if match.player2_id %>
            <%= link_to(image_tag(p[2].image, size: "30x30", alt: p[2].name), p[2]) if match.player3_id %>
            <%= link_to(image_tag(p[3].image, size: "30x30", alt: p[3].name), p[3]) if match.player4_id %>
          </td>
          <td><%= match.start.to_s(:long) %></td>
          <td><%= match.end.to_s(:long) %></td>
          <td><%= match.court %></td>
          <td><%= link_to("Match Page", match, {:class => "btn btn-info btn-sm"}) %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/matches/show.html.erb
<%= if notice and notice.is_a?(Array) then content_tag(:div, content_tag(:p, notice[0]), class: notice[1]) end %>

<% p = get_player_list(@match); %>


<%= form_for(@match, url: {action: "join"}) do |f| %>
	<%= f.submit 'Join/Leave', :class => "btn btn-success btn-lg btn-block" %>
	<br />
<% end %>


<div class="panel panel-primary", id="details", style="float:left;width:40%;min-height:490px;">
<div class="panel-heading">
<h3 class="panel-title"> Match Details</h3>
</div>
<div class="panel-body">


<div class="panel panel-default">
<div class="panel-heading">Players</div>
<div class="panel-body">
<p>
  <%= link_to(p[0].try(:name) + " (Host)", p[0]) %>
</p>

<p>
  <% if p[1] %>
    <%= form_for(@match, url: {action: "kick"}) do |f| %>
    <%= link_to(p[1].name, p[1]) %>
    	<% if @host%>  <!-- only host can kick people out -->
    	<%= f.hidden_field :pid, :value => p[1].id %>
    	<%= f.submit 'kick out', :class => "btn btn-danger btn-xs", html:{style: style="display:inline"} %> 
    	<% end %>
    <% end %>
  <% end %>
</p>


<p>
  <% if p[2] %>
    <%= form_for(@match, url: {action: "kick"}) do |f| %>
    <%= link_to(p[2].name, p[2]) %>
      <% if @host%> 
      <%= f.hidden_field :pid, :value => p[2].id %>
      <%= f.submit 'kick out', :class => "btn btn-danger btn-xs", html:{style: style="display:inline"} %> 
      <% end %>
    <% end %>
  <% end %>
</p>

<p>
  <% if p[3] %>
    <%= form_for(@match, url: {action: "kick"}) do |f| %>
    <%= link_to(p[3].name, p[3]) %>
      <% if @host%> 
      <%= f.hidden_field :pid, :value => p[3].id %>
      <%= f.submit 'kick out', :class => "btn btn-danger btn-xs", html:{style: style="display:inline"} %> 
      <% end %>
    <% end %>
  <% end %>
</p>

</div>
</div>


<div class="panel panel-default">
<div class="panel-body" >
<p>
  <strong>Start Time:</strong>
  <%= @match.start.to_s(:long) %>
</p>

<p>
  <strong>End Time:</strong>
  <%= (@match.end or @match.end_date).to_s(:long) %>
</p>

<p style="word-wrap: break-word;">
  <strong>Court:</strong>
  <%= @match.court %>
</p>

<p style="word-wrap: break-word;">
  <strong>Description:</strong>
  <%= @match.desc %>
</p>

<p>
  <strong>Match Type:</strong>
  <%= @match.match_type %>
</p>

<p>
  <strong>Location:</strong>
  <%= @match.location %>
</p>

<%= link_to('Edit', edit_match_path(@match)) if @host %>
</div>
</div>

</div>
</div>

<!-- CHAT ROOM -->
<%= content_tag :div, class: "chatbox", id: "chatbox_" + @conversation.id.to_s, style: "display:block;float:right;width:59.5%;padding-left:1%;position:static" do -%>
<div class="chatboxhead" style="background-color: #337ab7;">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1>Chat Room</h1>
  </div>
  <div class="chatboxoptions"></div>
  <br clear="all"/>
</div>
<div class="chatboxcontent", id="chat_content_id", style="width:auto;height:400px">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => {id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", style: 'width: 100%;', "data-cid" => @conversation.id %>
  <% end %>
</div>
<% end %>


<%= subscribe_to conversation_path(@conversation) %>