config/routes.rb
Myapp::Application.routes.draw do
  
  resources :matches
  get "view_profile", to: 'users#show'
  get "developers/index"
  get "users/show"
  get "about_us", to: 'developers#index'
  get 'auth/:provider/callback', to: 'users#new'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'users/conversations/:id', to: 'conversations#show'

  get "find_matches", to: "matches#find_matches"
  match '/matches/:id/join', to: 'matches#join', via: [:patch]
  match '/matches/:id/kick', to: 'matches#kick', via: [:patch]
  match '/find_matches/carousel', to: 'matches#carousel', via: [:post]
  
  get "faq", to: 'faq#index'
  
  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  get "home/index"

root to: 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Tennis Matchmaker</title>
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" media="screen" rel="stylesheet" />
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <meta content='<%= !current_user.nil? ? current_user.id : "" %>' name='user-id'/>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <%# Header and navigation bar. %>
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <%# Logo. %>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span> 
                    </button>
                    <%= link_to image_tag("logo-full-small.png", alt: "Tennis Matchmaker"), root_path, class: "navbar-logo" %> 
                </div>
                <%# Main nav links. %>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li><%= link_to "Home", root_path %></li>
                        <%# Signed-in users can find and create matches. %>
                        <% if current_user %>
                        <li><%= link_to "Find Matches", "/find_matches" %></li>
                        <li><%= link_to "Create Match", new_match_path %></li>
                        <li><%= link_to "My Matches", matches_path %></li>
                        <% end %>
                        <li><%= link_to "FAQ", "/faq" %></li>
                        <li><%= link_to "About Us", "/about_us" %></li>
                    </ul>
                    <%# Sign-in/out buttons, profile dropdown links. %>
                    <ul class="nav navbar-nav navbar-right">
                        <%# Google+ sign-in button, hide when user signed in. %>
                        <% if !current_user %>
                        <li>
                            <div>
                                <%= link_to image_tag("Red-signin-Medium-base-32dp.png", alt: "Sign in"), "/auth/google_oauth2", id: "sign_in", class: "navbar-signin" %>
                            </div>
                        </li>
                        <%# User dropdown menu, hide when user signed out. %>
                        <% else %>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.name %><span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <% if current_user.image %>
                                <li class="dropdown-menu-list-profilepicture"><%= image_tag(current_user.image, alt: "Profile picture", class: "img-thumbnail", size: "96x96") %></li>
                                <li class="divider"></li>
                                <% end %>
                                <li><%= link_to "View profile and messages", "/view_profile" %></li>
                                <li><%= link_to "My matches", "/matches" %></li>
                                <li class="divider"></li>
                                <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
                            </ul>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <%# Main content. %>
        <div class="container">
            <%= yield %>
        </div>
        <%# Footer. %>
        <br>
        <br>
        <footer class="navbar-fixed-bottom footer">
            <div class="container">
                <p class="text-muted">2015 TennisMatchmaker.co No Rights Reserved.</p>
            </div>
        </footer>
    </body>

    <% if current_user %>
    <script type="text/javascript">
        channel = <%= raw ('"' + '/notifications' + current_user.id.to_s + '"') %>
        PrivatePub.subscribe(channel, function(data) {
        var sender_id = data.sid;
        var recipient_id = data.rip;
        var conversation_id = data.cid;
        $.post("/conversations", { sender_id: sender_id, recipient_id: recipient_id }, function (data) {
            chatBox.chatWith(conversation_id);
        });
        });
    </script>
    <%= subscribe_to "/notifications" + current_user.id.to_s %>
    <% end %>
</html>